# -*- coding: utf-8 -*-
"""E3_PCN_mejorado.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16k4_AXKFvYiCh-OGU-SV1tqwOToUJTwb
"""

from google.colab import drive
drive.mount('/content/drive')

"""### PCN
`/content` se borra entera al terminar cada sesión de Colab, así que si
clonamos ahí hay que volver a descargar el repo cada vez. En vez de eso,
lo clonamos DENTRO de Google Drive (ya montado arriba) la primera vez, y
las siguientes veces simplemente lo detectamos y lo reutilizamos.
"""

# Commented out IPython magic to ensure Python compatibility.
ruta_repo = "/content/drive/MyDrive/Datos_E2/PCN-PyTorch"

import os
if not os.path.exists(ruta_repo):
    print("Repo no encontrado en Drive, clonando (solo la primera vez)...")
    !git clone https://github.com/qinglew/PCN-PyTorch.git {ruta_repo}
else:
    print("Repo ya existe en Drive, reutilizando -> no hace falta clonar de nuevo")

# %cd {ruta_repo}

"""### Imports generales"""

import os, glob, random
import numpy as np
import torch
from torch.utils.data import Dataset, DataLoader, Subset

# Semilla fija
SEED = 42
random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)

"""### Datos (carga y formato)
- Hay 61 pares (completo/roto).
- Cada par son dos archivos .npy
- Shape: (2048, 3) — 2.048 puntos, coordenadas XYZ
- Dtype: float32
- Normalización: centrado en el origen, escalado a esfera unidad
"""

ruta_datos ="/content/drive/MyDrive/Datos_E2/Fantastik_Break_Preprocesado"
print(os.listdir(ruta_datos)[:10])

class FantasticBreaksDataset(Dataset):
    """
    augmentar=True activa augmentación (rotación aleatoria en Z + jitter gaussiano
    ligero en la nube rota). Con solo ~60 pares reales, la augmentación es la forma
    más barata de darle al modelo más variedad efectiva sin datos nuevos.
    La rotación se aplica IGUAL a roto y completo para no romper la correspondencia
    punto-a-punto entre ambos. El jitter solo se aplica a la entrada (roto), nunca
    al ground truth.
    """
    def __init__(self, carpeta, augmentar=False, jitter_std=0.01):
        self.pares = []
        self.augmentar = augmentar
        self.jitter_std = jitter_std
        rotos = sorted(glob.glob(os.path.join(carpeta, "*_roto.npy")))
        for r in rotos:
            c = r.replace("_roto.npy", "_completo.npy")
            if os.path.exists(c):
                self.pares.append((r, c))

    def __len__(self):
        return len(self.pares)

    def _augmentar(self, roto, completo):
        # Rotación aleatoria alrededor del eje Z (misma rotación para los dos)
        theta = np.random.uniform(0, 2 * np.pi)
        c, s = np.cos(theta), np.sin(theta)
        R = np.array([[c, -s, 0],
                      [s,  c, 0],
                      [0,  0, 1]], dtype=np.float32)
        roto = roto @ R.T
        completo = completo @ R.T

        # Jitter gaussiano leve solo en la entrada rota (simula ruido de escaneo)
        roto = roto + np.random.normal(0, self.jitter_std, roto.shape).astype(np.float32)

        return roto, completo

    def __getitem__(self, idx):
        r_path, c_path = self.pares[idx]
        roto = np.load(r_path).astype(np.float32)
        completo = np.load(c_path).astype(np.float32)

        if self.augmentar:
            roto, completo = self._augmentar(roto, completo)

        return torch.from_numpy(roto), torch.from_numpy(completo)

# Dataset base (sin augmentar) para poder ver cuántos pares hay y para validación
dataset_base = FantasticBreaksDataset(ruta_datos, augmentar=False)
print(f"Pares encontrados: {len(dataset_base)}")

"""### División de los datos
Train / validation / test

Nota: se hace un split por índices (no random_split) para poder tener dos
instancias del dataset -- una CON augmentación (para train) y otra SIN
augmentación (para validación) -- pero compartiendo exactamente los mismos
índices de división.
"""

n_val = 8
n_train = len(dataset_base) - n_val  # 53

indices = list(range(len(dataset_base)))
random.shuffle(indices)
train_idx, val_idx = indices[:n_train], indices[n_train:]

dataset_train_aug = FantasticBreaksDataset(ruta_datos, augmentar=True, jitter_std=0.01)

train_set = Subset(dataset_train_aug, train_idx)   # con augmentación
val_set = Subset(dataset_base, val_idx)             # sin augmentación, datos limpios

train_loader = DataLoader(train_set, batch_size=4, shuffle=True)
val_loader = DataLoader(val_set, batch_size=4, shuffle=False)

print(f"Train: {len(train_set)} | Val: {len(val_set)}")

"""### Cargar Modelo"""

from models import PCN

model = PCN(num_dense=2048, latent_dim=1024, grid_size=4).cuda()
print("Modelo cargado")

import importlib

# Arreglo de compatibilidad: la librería usa una función antigua que ya no existe en Python 3.12
if not hasattr(importlib, "find_loader"):
    importlib.find_loader = lambda name: importlib.util.find_spec(name)

# La extensión de Chamfer Distance se compila vía JIT en el propio "import"
# (por eso aparece el mensaje "Jitting Chamfer 3D"), y ese proceso necesita
# el paquete "ninja" instalado en el sistema -- Colab no lo trae por defecto.
!pip install -q ninja

def cd_loss_L1(pcs1, pcs2):
    # pcs1: (B, N, 3), pcs2: (B, M, 3)
    dist = torch.cdist(pcs1, pcs2, p=2)          # (B, N, M) distancias euclídeas
    dist1 = dist.min(dim=2)[0].mean(dim=1)        # cada punto de pcs1 -> su vecino más cercano en pcs2
    dist2 = dist.min(dim=1)[0].mean(dim=1)        # cada punto de pcs2 -> su vecino más cercano en pcs1
    return (dist1.mean() + dist2.mean()) / 2.0

print("Chamfer Distance lista (implementación PyTorch, sin compilación)")

"""### Entrenamiento
Mejoras respecto a la primera versión (mismos datos, sin tocar arquitectura):

1. **Alpha annealing**: en el paper original de PCN la loss "dense" se pondera
   con un peso alpha que empieza bajo y crece con las épocas, en vez de sumar
   coarse+dense a partes iguales desde el principio. Así el modelo primero
   aprende la forma gruesa y luego afina el detalle.
2. **LR scheduler**: decaimiento del learning rate cada cierto número de
   épocas, en vez de mantenerlo constante todo el entrenamiento.
3. **Guardado del mejor checkpoint según loss de VALIDACIÓN** (no solo cada
   N épocas), que es lo que realmente nos interesa.
4. **Early stopping** simple por paciencia, para no seguir entrenando si la
   validación deja de mejorar.
5. Historial de losses guardado para poder graficar la curva train vs val.
"""

import torch.optim as optim

optimizer = optim.Adam(model.parameters(), lr=0.0001, betas=(0.9, 0.999))
scheduler = optim.lr_scheduler.StepLR(optimizer, step_size=40, gamma=0.5)

def alpha_para_epoca(epoca, total_epocas):
    progreso = epoca / total_epocas
    if progreso < 0.2:
        return 0.01
    elif progreso < 0.4:
        return 0.1
    elif progreso < 0.6:
        return 0.5
    elif progreso < 0.8:
        return 1.0
    else:
        return 2.0

epocas = 300
ruta_checkpoints = "/content/drive/MyDrive/Datos_E2/checkpoints_pcn"
os.makedirs(ruta_checkpoints, exist_ok=True)

historial_train = []
historial_val = []
mejor_val = float("inf")
paciencia = 40          # épocas sin mejora antes de parar
epocas_sin_mejora = 0

for epoca in range(1, epocas + 1):
    model.train()
    loss_total = 0.0
    alpha = alpha_para_epoca(epoca, epocas)

    for roto, completo in train_loader:
        roto, completo = roto.cuda(), completo.cuda()

        optimizer.zero_grad()
        coarse_pred, dense_pred = model(roto)

        loss1 = cd_loss_L1(coarse_pred, completo)
        loss2 = cd_loss_L1(dense_pred, completo)
        loss = loss1 + alpha * loss2

        loss.backward()
        optimizer.step()

        loss_total += loss.item()

    scheduler.step()
    loss_media = loss_total / len(train_loader)
    historial_train.append(loss_media)

    model.eval()
    loss_val_total = 0.0
    with torch.no_grad():
        for roto, completo in val_loader:
            roto, completo = roto.cuda(), completo.cuda()
            coarse_pred, dense_pred = model(roto)
            loss_val_total += cd_loss_L1(dense_pred, completo).item()
    loss_val_media = loss_val_total / len(val_loader)
    historial_val.append(loss_val_media)

    if epoca % 5 == 0 or epoca == 1:
        lr_actual = optimizer.param_groups[0]["lr"]
        print(f"Época {epoca}/{epocas} - train: {loss_media:.6f} - val: {loss_val_media:.6f} "
              f"- alpha: {alpha:.2f} - lr: {lr_actual:.2e}")

    if loss_val_media < mejor_val:
        mejor_val = loss_val_media
        epocas_sin_mejora = 0
        torch.save(model.state_dict(), f"{ruta_checkpoints}/pcn_mejor.pt")
    else:
        epocas_sin_mejora += 1

    if epoca % 25 == 0:
        torch.save(model.state_dict(), f"{ruta_checkpoints}/pcn_epoca{epoca}.pt")

    if epocas_sin_mejora >= paciencia:
        print(f"Sin mejora en validación durante {paciencia} épocas -> early stopping en época {epoca}")
        break

print(f"Entrenamiento terminado. Mejor loss de validación: {mejor_val:.6f}")

model.load_state_dict(torch.load(f"{ruta_checkpoints}/pcn_mejor.pt"))
print("Cargados los pesos del mejor checkpoint (según val loss)")

"""### Curva de entrenamiento"""

import matplotlib.pyplot as plt

plt.figure(figsize=(8, 5))
plt.plot(historial_train, label="Train")
plt.plot(historial_val, label="Validación")
plt.xlabel("Época")
plt.ylabel("Chamfer L1 loss")
plt.legend()
plt.title("Curva de entrenamiento")
plt.show()

"""### Visualizar el resultado (mejor checkpoint según val loss)"""

def visualizar_reconstruccion(roto, prediccion, completo, titulo=""):
    fig = plt.figure(figsize=(15, 5))

    datos = [
        (roto, "Entrada (rota)"),
        (prediccion, "Predicción del modelo"),
        (completo, "Ground truth (completo)")
    ]

    for i, (puntos, nombre) in enumerate(datos):
        ax = fig.add_subplot(1, 3, i + 1, projection='3d')
        puntos = puntos.cpu().numpy()
        ax.scatter(puntos[:, 0], puntos[:, 1], puntos[:, 2], s=2, alpha=0.6)
        ax.set_title(nombre)
        ax.set_xlim(-1, 1)
        ax.set_ylim(-1, 1)
        ax.set_zlim(-1, 1)

    plt.suptitle(titulo)
    plt.tight_layout()
    plt.show()

model.eval()

# Visualizamos varios ejemplos de validación, no solo el primero, para hacernos
# una idea más fiable de si el modelo generaliza o solo acierta en un caso suelto.
n_ejemplos = min(3, len(val_set))
for i in range(n_ejemplos):
    roto, completo = val_set[i]
    roto_batch = roto.unsqueeze(0).cuda()  # añadir dimensión de batch: (1, 2048, 3)

    with torch.no_grad():
        coarse_pred, dense_pred = model(roto_batch)

    prediccion = dense_pred[0]
    prediccion_coarse = coarse_pred[0]

    visualizar_reconstruccion(roto, prediccion, completo, titulo=f"Validación #{i} — FINE")
    visualizar_reconstruccion(roto, prediccion_coarse, completo, titulo=f"Validación #{i} — COARSE")

"""### Notas
La reconstrucción sigue saliendo dispersa/en forma de rejilla en
  vez de una geometría reconocible.  
  53 pares de entrenamiento son muy pocos
  para que PCN aprenda a "doblar" su rejilla base en formas de vasija
  variadas y generalizar a un caso de validación.
- Siguiente paso  (ver `PLANIFICACION.md`, tarea de agosto): generar
  roturas sintéticas sobre los ~2.367 modelos de ShapeNet/Objaverse ya
  limpios, pre-entrenar PCN ahí, y usar Fantastic Breaks solo para
  fine-tuning final. Con eso el modelo debería dejar de depender de 53
  ejemplos para aprender la geometría general de una vasija.
"""