# -*- coding: utf-8 -*-
"""E3.PCN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nF2x0i0cWRnsX8hysUXRv3lRwiaYZzLG

### Montar el Drive
Conceder acceso a los archivos de Google Drive (para acceder a la base de datos fantastik_breaks_procesada).
"""

from google.colab import drive
drive.mount('/content/drive')

"""### PCN
Acceder al proyecto PNC ya clonado
"""

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/PCN-PyTorch

"""### Imports generales"""

import os, glob
import numpy as np
import torch
from torch.utils.data import Dataset, DataLoader, random_split

"""### Datos (carga y formato)
- Hay 61 pares (completo/roto).
- Cada par son dos archivos .npy
- Shape: (2048, 3) — 2.048 puntos, coordenadas XYZ
- Dtype: float32
- Normalización: centrado en el origen, escalado a esfera unidad


"""

ruta_datos ="/content/drive/MyDrive/Datos_E2/Fantastik_Break_Preprocesado"
print(os.listdir(ruta_datos)[:10])

class FantasticBreaksDataset(Dataset):
    def __init__(self, carpeta):
        self.pares = []
        rotos = sorted(glob.glob(os.path.join(carpeta, "*_roto.npy")))
        for r in rotos:
            c = r.replace("_roto.npy", "_completo.npy")
            if os.path.exists(c):
                self.pares.append((r, c))

    def __len__(self):
        return len(self.pares)

    def __getitem__(self, idx):
        r_path, c_path = self.pares[idx]
        roto = torch.from_numpy(np.load(r_path)).float()
        completo = torch.from_numpy(np.load(c_path)).float()
        return roto, completo

dataset = FantasticBreaksDataset(ruta_datos)
print(f"Pares encontrados: {len(dataset)}")

"""### División de los datos
Train / validation / test
"""

n_val = 8
n_train = len(dataset) - n_val  # 53

train_set, val_set = random_split(dataset, [n_train, n_val])

train_loader = DataLoader(train_set, batch_size=4, shuffle=True)
val_loader = DataLoader(val_set, batch_size=4, shuffle=False)

print(f"Train: {len(train_set)} | Val: {len(val_set)}")

"""### Cargar Modelo"""

from models import PCN

model = PCN(num_dense=2048, latent_dim=1024, grid_size=4).cuda()
print("Modelo cargado")

import importlib

# Arreglo de compatibilidad: la librería usa una función antigua que ya no existe en Python 3.12
if not hasattr(importlib, "find_loader"):
    importlib.find_loader = lambda name: importlib.util.find_spec(name)

from extensions.chamfer_distance.chamfer_distance import ChamferDistance

CD = ChamferDistance()

def cd_loss_L1(pcs1, pcs2):
    dist1, dist2 = CD(pcs1, pcs2)
    dist1 = torch.sqrt(dist1)
    dist2 = torch.sqrt(dist2)
    return (torch.mean(dist1) + torch.mean(dist2)) / 2.0

print("Chamfer Distance lista")

"""### Entrenamiento 1
20 epocas
"""

import torch.optim as optim

optimizer = optim.Adam(model.parameters(), lr=0.0001, betas=(0.9, 0.999))

epocas = 20 # como valor inicial
ruta_checkpoints = "/content/drive/MyDrive/Datos_E2/checkpoints_pcn"
os.makedirs(ruta_checkpoints, exist_ok=True)

for epoca in range(1, epocas + 1):
    model.train()
    loss_total = 0.0

    for roto, completo in train_loader:
        roto, completo = roto.cuda(), completo.cuda()

        optimizer.zero_grad()
        coarse_pred, dense_pred = model(roto)

        loss1 = cd_loss_L1(coarse_pred, completo)
        loss2 = cd_loss_L1(dense_pred, completo)
        loss = loss1 + loss2

        loss.backward()
        optimizer.step()

        loss_total += loss.item()

    loss_media = loss_total / len(train_loader)
    print(f"Época {epoca}/{epocas} - loss: {loss_media:.6f}")

    # guardar checkpoint cada 5 épocas
    if epoca % 5 == 0:
        torch.save(model.state_dict(), f"{ruta_checkpoints}/pcn_epoca{epoca}.pt")
        print(f"  -> checkpoint guardado")

print("Entrenamiento terminado")

"""#### Observaciones
Observando la tendencia del valor Loss se observa que el modelo está aprendiendo correctamente:  empezó en 0.59 y ha bajado hasta aprox 0.25.  

- Primeras épocas (1-4): bajada rápida y clara — el modelo está aprendiendo lo más básico (la forma general de una vasija).
- A partir de la época 10-15: la bajada se hace más lenta y con algo de vaivén (sube y baja un poco entre épocas). Esto es normal con pocos datos.
- Últimas épocas: parece que está empezando a estabilizarse alrededor de 0.24-0.27, lo que sugiere que quizás con más épocas seguiría bajando un poco más, pero ya no a la misma velocidad.
"""

model.eval()
loss_val_total = 0.0

with torch.no_grad():
    for roto, completo in val_loader:
        roto, completo = roto.cuda(), completo.cuda()
        coarse_pred, dense_pred = model(roto)
        loss = cd_loss_L1(dense_pred, completo)
        loss_val_total += loss.item()

loss_val_media = loss_val_total / len(val_loader)
print(f"Loss de validación: {loss_val_media:.6f}")

"""### Resumen 1º entrenamiento
- 53 pares train / 8 pares validación
- PCN, 2048 puntos, 20 épocas
- Loss train final: 0.267 (bajando desde 0.594)
- Loss validación: 0.216
- Sin señales de overfitting

### Visualizar el resultado
"""

import matplotlib.pyplot as plt

def visualizar_reconstruccion(roto, prediccion, completo, titulo=""):
    fig = plt.figure(figsize=(15, 5))

    datos = [
        (roto, "Entrada (rota)"),
        (prediccion, "Predicción del modelo"),
        (completo, "Ground truth (completo)")
    ]

    for i, (puntos, nombre) in enumerate(datos):
        ax = fig.add_subplot(1, 3, i + 1, projection='3d')
        puntos = puntos.cpu().numpy()
        ax.scatter(puntos[:, 0], puntos[:, 1], puntos[:, 2], s=2, alpha=0.6)
        ax.set_title(nombre)
        ax.set_xlim(-1, 1)
        ax.set_ylim(-1, 1)
        ax.set_zlim(-1, 1)

    plt.suptitle(titulo)
    plt.tight_layout()
    plt.show()

model.eval()

# coger un solo ejemplo de validación
roto, completo = val_set[0]
roto_batch = roto.unsqueeze(0).cuda()  # añadir dimensión de batch: (1, 2048, 3)

with torch.no_grad():
    coarse_pred, dense_pred = model(roto_batch)

# quitar la dimensión de batch para visualizar
prediccion = dense_pred[0]

visualizar_reconstruccion(roto, prediccion, completo, titulo="Ejemplo de validación")

prediccion_coarse = coarse_pred[0]
visualizar_reconstruccion(roto, prediccion_coarse, completo, titulo="Predicción COARSE (basta)")

"""Al visulaizar el modelo se observa que hacen falta más épocas.

### Entrenamiento 2
Aumentar el numero de epocas a 150
"""

epocas = 150
ruta_checkpoints = "/content/drive/MyDrive/Datos_E2/checkpoints_pcn"

for epoca in range(1, epocas + 1):
    model.train()
    loss_total = 0.0

    for roto, completo in train_loader:
        roto, completo = roto.cuda(), completo.cuda()

        optimizer.zero_grad()
        coarse_pred, dense_pred = model(roto)

        loss1 = cd_loss_L1(coarse_pred, completo)
        loss2 = cd_loss_L1(dense_pred, completo)
        loss = loss1 + loss2

        loss.backward()
        optimizer.step()

        loss_total += loss.item()

    loss_media = loss_total / len(train_loader)

    if epoca % 10 == 0:
        print(f"Época {epoca}/{epocas} - loss: {loss_media:.6f}")
        torch.save(model.state_dict(), f"{ruta_checkpoints}/pcn_epoca_extra{epoca}.pt")

print("Entrenamiento extendido terminado")

model.eval()
loss_val_total = 0.0

with torch.no_grad():
    for roto, completo in val_loader:
        roto, completo = roto.cuda(), completo.cuda()
        coarse_pred, dense_pred = model(roto)
        loss = cd_loss_L1(dense_pred, completo)
        loss_val_total += loss.item()

loss_val_media = loss_val_total / len(val_loader)
print(f"Loss de validación: {loss_val_media:.6f}")

model.eval()
roto, completo = val_set[0]
roto_batch = roto.unsqueeze(0).cuda()

with torch.no_grad():
    coarse_pred, dense_pred = model(roto_batch)

prediccion = dense_pred[0]
prediccion_coarse = coarse_pred[0]

visualizar_reconstruccion(roto, prediccion_coarse, completo, titulo="Predicción COARSE (150 épocas)")
visualizar_reconstruccion(roto, prediccion, completo, titulo="Predicción FINAL (150 épocas)")

"""### Observaciones
- La loss de entrenamiento descendió de forma consistente a lo largo del entrenamiento, pasando de 0.595 en la primera época a 0.137 en la época 150.
- La loss de validación se mantuvo en un rango similar (0.216 tras las primeras 20 épocas), sin evidencia de overfitting severo entre train y validación.
- Pese a la mejora numérica de la loss, la inspección visual de las predicciones (tanto en la salida coarse como en la fine) muestra que el modelo no logra reconstruir una geometría reconocible como vasija: las predicciones adoptan una distribución dispersa y aproximadamente regular en forma de rejilla, en contraste con la superficie coherente de las nubes ground truth.
"""